## web cat dog 3가지 도커파일을 각각 ecr에 업로드하는 gitaction yaml

name: cats and dogs gitaction

on: workflow_dispatch

env:
  AWS_ACCESS_ROLE: ${{ secrets.AWS_ACCESS_ROLE }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_CATS_REPO: ${{ vars.AWS_CATS_REPO }}
  AWS_DOGS_REPO: ${{ vars.AWS_DOGS_REPO }}
  AWS_WEBS_REPO: ${{ vars.AWS_WEBS.REPO }}
  
permissions:
  contents: read
  id-token: write

jobs:
  webs-jobs:
    name: build-web-container
    runs-on: ubuntu:latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ACCESS_ROLE }}
          role-duration-seconds: 900
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  cats-jobs:
    name: build-cat- container
    runs-on: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ACCESS_ROLE }}
          role-duration-seconds: 900
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  dogs-jobs:
    name: build-dogs-container
    runs-on: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ACCESS_ROLE }}
          role-duration-seconds: 900
  
      - name: Login to A mazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
