## web cat dog 3가지 도커파일을 각각 ecr에 업로드하는 gitaction yaml

name: cats and dogs gitaction

on: 
  push:
    branches:
      - main

env:
  AWS_ACCESS_ROLE: ${{ secrets.AWS_ACCESS_ROLE }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_CATS_REPO: ${{ vars.AWS_CATS_REPO }}
  AWS_DOGS_REPO: ${{ vars.AWS_DOGS_REPO }}
  AWS_WEBS_REPO: ${{ vars.AWS_WEBS_REPO }}
  
permissions:
  contents: read
  id-token: write

jobs:
  # versioning:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     tag: ${{ steps.version_step.outputs.tag }}
  #   steps:
  #     - id: version_step
  #       name: set version with current date
  #       run: |
  #         sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
  #         echo "tag=$(date +'%Y%m%d.%H%M%S')" >> "$GITHUB_OUTPUT"
  versioning:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-date.outputs.tag }}
    steps:  
      - id: get-date
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "tag=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
  
  webs-jobs:
    needs: versioning
    name: build-web-container
    runs-on: ubuntu-latest    # 태그 명시시 : 가 아닌 -
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ACCESS_ROLE }}
          role-duration-seconds: 900
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: move to webs
        run: |
          mv web/* ./

      - name: docker build to webs
        run: |
          docker build -t ${{ env.AWS_WEBS_REPO }}:${{ needs.versioning.outputs.tag }} .
          docker images

      - name: push repo
        run: |
          docker push ${{ env.AWS_WEBS_REPO }}:${{ needs.versioning.outputs.tag }}

  cats-jobs:
    needs: versioning
    name: build-cat- container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ACCESS_ROLE }}
          role-duration-seconds: 900
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: move to cats
        run: |
          mv cats/* ./

      - name: docker build to cats
        run: |
          docker build -t ${{ env.AWS_CATS_REPO }}:${{ needs.versioning.outputs.tag }} .
          docker images

      - name: push repo
        run: |
          docker push ${{ env.AWS_CATS_REPO }}:${{ needs.versioning.outputs.tag }}

  dogs-jobs:
    needs: versioning
    name: build-dogs-container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ACCESS_ROLE }}
          role-duration-seconds: 900
  
      - name: Login to A mazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: move to dogs
        run: |
          mv dogs/* ./

      - name: docker build to dogs
        run: |
          docker build -t ${{ env.AWS_DOGS_REPO }}:${{ needs.versioning.outputs.tag }} .
          docker images

      - name: push repo
        run: |
          docker push ${{ env.AWS_DOGS_REPO }}:${{ needs.versioning.outputs.tag }}

